### ISSUE TITLE
passing arguments

### ISSUE THREAD

**Issue by peh** [mikaelbr/node-osascript#1]
hey, is there any way one can pass arguments to the script that is being called
i would like to let osascript run a js file and pass some arguments to that script.

**Comment by mikaelbr** [comment]
Hi. Thanks for your issue. I've added argument support now: https://github.com/mikaelbr/node-osascript/releases/tag/v1.1.0

Hope it works out all right.

**Comment by peh** [comment]
hey, i think you have not released that to npm no?

**Comment by mikaelbr** [comment]
Oh, sorry. Apparently that slipped my mind. Published now.
